theme: jekyll-theme-cayman
title: 'uBlacklist for Safari'
description: 'Search engine filter for safariSearch engine filter for safari'
# google_analytics: G-NWQY9CVPF7

show_ios_download_btn: true
ios_download_url: 'https://www.google.com'
ios_download_btn_title: 'Download on the App Store'

show_android_download_btn: true
android_download_url: 'https://www.google.com'
android_download_btn_title: 'Download on the Google Play'

show_web_download_btn: true
web_download_url: 'https://www.google.com'
web_download_btn_title: 'HomePage'

show_email_link: true
email: 'group.leafy@gmail.com'

show_terms_link: true
terms_link: 'terms'

show_privacy_link: true
privacy_link: 'privacy'

copyright: 'Copyright Group-Leafy. All rights reserved'

show_app_icon: true
app_icon: 'assets/image/icon.png'

show_screenshot: true
screenshots: ['assets/image/screenshot.png', 'assets/image/screenshot.png', 'assets/image/screenshot.png', 'assets/image/screenshot.png', 'assets/image/screenshot.png', 'assets/image/screenshot.png']